- include/frg/expected.hpp
- include/frg/formatting.hpp
this is an API breaking change, maybe i should also finish using ``frg::expected`` for the formatters as well before we merge this to avoid having to break the API again at a later stage?
> formatting: use frg::expected in formatting agents

- include/frg/formatting.hpp
This PR fixes a number of issues:
1. Adds support for `'+'` and `' '` flags when printing signed integers. This fixes managarm/mlibc#229.
1. When `'#'` is used with `'o'`, only print a leading zero if the number is non-zero.
1. When `'X'` is used, use uppercase letters for hexadecimal digits.
1. When `'#'` is used with `'x'` or `'X'`, prepend `"0x"` or `"0X"` respectively.
The relevant tests are added in managarm/mlibc#248.
> formatting: Fix '+', ' ', '#' and 'X'

- include/frg/formatting.hpp
This PR fixes various issues w.r.t formatting:
* Handles inf / nan in `%f` and `%F`
* Handles negatives in `%f` and `%F`
* Handles padding and justification in `%f` and `%F`
* Assumes precision is zero when `.` is present but no number follows (fixes managarm/mlibc#209)
* Assumes precision to be 6 when no `.` is present in `%f` and `%F`
* Allows precision when working with unsigned integers (fixes managarm/mlibc#182)
There is still a lot more work to be done, especially around printing floating point numbers.
The relevant tests are added in managarm/mlibc#254.
> formatting: misc fixes

- include/frg/allocation.hpp
This is required under gcc 11.
> allocation: Add stddef include to get size_t

- include/frg/formatting.hpp
- include/frg/string.hpp
These changes are needed to have managarm compile with `-Werror -Wimplicit-fallthrough`.
> Small fixes for enabling stricter warnings in managarm

- include/frg/formatting.hpp
- include/frg/printf.hpp
We also give `%u` a quick refactor, because why not.
Tests added in https://github.com/managarm/mlibc/pull/380.
> printf: implement %h and %hh

- include/frg/printf.hpp
POSIX positional arguments are 1-indexed but the current code wrongly assumes that they're 0-indexed.
Fixes https://github.com/managarm/frigg/issues/16.
> printf: fix positional arguments

- meson.build
Some headers were previously not installed in `meson.build`.
> install missing headers

- include/frg/logging.hpp
This is needed for some un-copyable types.
> pass formatted object by reference

- include/frg/formatting.hpp
- tests/tests.cpp
This pr adds support for 'b', 'o' and 'i' format specifiers
Example:
```
("{:b}", 28) -> 11100 // 0b11100
("{:o}", 28) -> 34 // 034
("{:i}", 28) -> 28 // 28
```
> formatting: add support for binary, octal and alternative decimal format specifiers

- include/frg/formatting.hpp
This commit fixes error ``no member named 'get' in 'frg::tuple<>'`` which is thrown when no additional arguments are passed to frg::fmt Example:
```c++
frg::fmt("my text with additional {}", "args");
frg::fmt("my text"); // < error here
```
> formatting: allow passing no additional arguments to frg::fmt

- include/frg/eternal.hpp
- include/frg/formatting.hpp
this pr adds support for formatting characters and fixes this warning on clang 15:
```
builtin __has_trivial_destructor is deprecated; use __is_trivially_destructible instead
```
Example:
```c++
frg::fmt("character: {:c}, int: {}, int: {}, int: 0x{:X}", 'c', uint8_t('c'), 'c', 'c');
```
```
character: c, int: 99, int: 99, int 0x63
```
> formatting: support formatting characters

- include/frg/string.hpp
This change was needed for LLVM 16 to agree on our codebase.
Tested by booting Managarm.
> string: Remove operator!= for basic_string_view and basic_string

- include/frg/array.hpp
- tests/tests.cpp
Moves all get overloads for frg::array to frg namespace as Clang and GCC expect get to be in inner type's namespace. More info [here](https://en.cppreference.com/w/cpp/language/structured_binding) in Case 2.
> array: Fix structured bindings

- include/frg/formatting.hpp
- tests/tests.cpp
The current code fails for eg. 5.01 printing 5.000000 instead of 5.010000.
> printf: Fix a bug in float printing

- include/frg/spinlock.hpp
If multiple waiters call ::lock, next_ticket_ is pushed forward multiple times.
> spinlock: Fix ticket_spinlock::is_locked check

- include/frg/formatting.hpp
- include/frg/printf.hpp
- tests/tests.cpp
> printf: handle argument indices given by dollars in format strings

- include/frg/scope_exit.hpp
- meson.build
This class behaves similarly to `std::experimental::scope_exit`, see also: https://en.cppreference.com/w/cpp/experimental/scope_exit
> scope_exit: Add STL-like scope_exit class

- include/frg/expected.hpp
Hey - I noticed a missing return in the copy assignment operator for frigg's `expected<>` implementation.
> expected: added missing return statement

- include/frg/span.hpp
Add an array constructor to span, it is already possible using the begin + size constructor but it this is more convenient to use.
> span: allow construction from an array

- include/frg/formatting.hpp
- tests/tests.cpp
This seemed like a copy-paste error.
I tried adding a test, but the test target doesn't compile for me and I didn't look into it further.
macOS 15.3.2
googletest 1.17.0
> Fix float and double printing
